language: python

# 3.6 is listed first so it gets used for the later build stages
python:
  - "3.6"
  - "3.7-dev"

before_script:
  - pip install -U datasette pip wheel pytest

script:
  - pytest

cache:
    directories:
      - $HOME/.cache/pip

jobs:
  include:
    - stage: release tagged version
      if: tag IS present
      language: python
      python: 3.6
      script:
        - pip install -U pip wheel
      deploy:
        - provider: pypi
          user: simonw
          distributions: bdist_wheel
          password: ${PYPI_PASSWORD}
          on:
            branch: master
            tags: true
            repo: simonw/datasette-render-images
    - stage: Demonstrate tag alpha conditional
      if: (tag IS present) AND NOT (tag =~ [ab])
      python: 3.6
      script:
        - echo "This is running becaues a or b were not in the tag"
